apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: my-deploy
    env: staging 
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deploy
      env: staging
  template:
    metadata:
      labels:
        app: my-deploy
        env: staging
    spec:
      containers:
        - name: app
          image: nginx:latest
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"