apiVersion: v1
kind: Pod
metadata:
  name: pod-ok
  labels:
    app: my-app
    env: production
spec:
  containers:
    - name: app
      image: nginx:1.25.0
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"