apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  labels:
    app: my-app
    env: production
spec:
  containers:
    - name: app
      # image: nginx:latest
      image: nginx:1.25.0  
      resources:
        limits:
          cpu: "500m"     #  AJOUTER LIMITE CPU
          memory: "256Mi" # AJOUTER LIMITE MÉMOIRE