name: OPA Policy Check

on:
  push:
    branches: ["main", "dev"]

jobs:
  conftest-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.56.0/conftest_0.56.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.56.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run Kubernetes policy checks  # ← NOM CORRIGÉ
        run: |
          conftest test k8s-manifests/*.yaml --policy policies/ 